# USER SETTINGS
DETECT_FACES = True
DETECT_BODIES = True
DETECT_CONTOURS = True
SECONDS_RECORDING_AFTER_DETECTION = 5
CONTOUR_MIN_AREA = 5000

# GPIO PINS - BCM
RED_LED = 22
GREEN_LED = 13
BUTTON = 12
BUZZER = 4
